[phases.setup]

[phases.build]
cmds = [
    "python -m pip install --upgrade pip",
    "python manage.py collectstatic --noinput",
    "python manage.py migrate --noinput"
]

[start]
cmd = "daphne -b 0.0.0.0 -p 8000 config.asgi:application"
